version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # Giới hạn Heap Size là 1G
      # - pack.security.enrollment.enabled=true
      - ELASTIC_PASSWORD=my_own_password
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - efk
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    restart: always
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - efk
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    links: # Links kibana service to the elasticsearch container
      - elasticsearch
    depends_on:
      - elasticsearch
    restart: always
    ports: # Runs kibana service on default port 5601
      - 5601:5601
    environment: # Defined host configuration
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=my_own_password
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    networks:
      - efk

volumes:
  elasticsearch:

networks:
  efk: